name: test-twom-snap
version: 2018-07-20-01
summary: A test mostly empty snap
confinement: strict
grade: stable
description: Print out an emoji
base: core

architectures:
  - amd64

apps:
  twomtest:
    command: echo "☃"
    autostart: test-twom-snap.desktop

parts:
  empty:
    plugin: nil

