name: test-twom-snap
version: 2018-07-20-01
summary: A test mostly empty snap
confinement: strict
grade: stable
description: Print out an emoji

architectures:
  - amd64

apps:
  twomtest:
    command: echo "☃"

parts:
  empty:
    plugin: nil

